### ISSUE TITLE
exit code -11

### ISSUE THREAD

**Issue by farhud** [KumarRobotics/flir_gige#2]
Hi,
After running the node.launch I get this error message :

[ INFO] [1452390038.532432374]: /thermal: Initializing reconfigure server
[thermal-2] process has died [pid 23806, exit code -11, cmd /home/.../flir_gige/flir_gige_node __name:=thermal __log:=/home/.../log/2411da0c-b73b-11e5-86b6-b499bae3e2d0/thermal-2.log].
log file: /home/.../log/2411da0c-b73b-11e5-86b6-b499bae3e2d0/thermal-2*.log

could you please help me to solve this error.
thx

**Comment by versatran01** [comment]
could be that you forget to source the set_puregev_gen in the install folder.
Just do `source ./install/set_puregev_gen` in the package folder
I updated the readme file accordingly.

**Comment by farhud** [comment]
Yes that was the problem. Sourcing the file solved it.
thank you.

**Comment by nicaima** [comment]
Hello,
When I install the eBUS SDK in Ubuntu14.04 64bit LTS,the ebUniversalProForEthernet-x86_64.ko cannot be build seccesful,the error is :/opt/pleora/ebus_sdk/Ubuntu-14.04-x86_64/module/ebUniversalProForEthernet/OS_KMLNetwork.c:96:2: error: too many arguments to function ‘sock_sendmsg’
  lReturn = sock_sendmsg( lSocket, &lMessage, lTotalSize );
  ^
Thank a lot!
![error1](https://cloud.githubusercontent.com/assets/17984181/19334170/cdf790c2-912c-11e6-876d-f88e9c707fa0.png)
