### ISSUE TITLE
The error about installing eBus SDK in Ubuntu

### ISSUE THREAD

**Issue by nicaima** [KumarRobotics/flir_gige#5]
Hello,
When I install the eBUS SDK in Ubuntu14.04 64bit LTS,the ebUniversalProForEthernet-x86_64.ko cannot be build seccesful,the error is :/opt/pleora/ebus_sdk/Ubuntu-14.04-x86_64/module/ebUniversalProForEthernet/OS_KMLNetwork.c:96:2: error: too many arguments to function ‘sock_sendmsg’
  lReturn = sock_sendmsg( lSocket, &lMessage, lTotalSize );
  ^
Thank a lot!
![error1](https://cloud.githubusercontent.com/assets/17984181/19334197/f75fdf28-912c-11e6-8f4e-03a9696a31b5.png)

**Comment by versatran01** [comment]
Is this a problem with installing eBus SDK or with compiling the flir driver?

**Comment by nicaima** [comment]
The Problem is installing eBus SDK. But I can build your driver. I don't know what to do.

**Comment by versatran01** [comment]
Is this building sample code? you can skip that if it doesn't build.

**Comment by nicaima** [comment]
Build ebUniversalProForEthernet-x86_64.ko  ,the eBUS SDK for Linux  Quick Start Guide said use have to build and load it .

**Comment by nicaima** [comment]
Hello,
 I finally resolve the error by reinstalling Ubuntu.
Thank you a lot!
